name: crypto-charts
on:
  push:
    branches: [master]

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    name: "Deploy front-end"
    
    steps:
      - name: Setup repo
        uses: actions/checkout@v3

      - name: install deps
        uses: borales/actions-yarn@v4
        with:
          cmd: install

      - name: build
        uses: borales/actions-yarn@v4
        with:
          cmd: build

      - name: Deploy to crypto-charts-os.surge.sh
        uses: dswistowski/surge-sh-action@v1
        with:
          domain: 'crypto-charts-os.surge.sh'
          project: './build/'
          login: ${{ secrets.surge_login }}
          token: ${{ secrets.surge_token }}
